### ISSUE TITLE
Inconsistent case for FID property of different events

### ISSUE THREAD

**Issue by Tofystedeth** [Somfic/EliteAPI#88]
The FID property, which is present for both the CommanderEvent and LoadGameEvent is spelled "FID" in the CommanderEvent and "Fid" in the LoadGameEvent.

**Comment by Somfic** [comment]
The correct spelling of this property should be `Fid`.

This issue is fixed on the dev branch, see the [Commander event](https://github.com/EliteAPI/EliteAPI/blob/aa9480d854319c4f5023c3f04faf45fe5dc1c1ab/EliteAPI/Event/Models/CommanderEvent.cs#L14) and [LoadGame event](https://github.com/EliteAPI/EliteAPI/blob/aa9480d854319c4f5023c3f04faf45fe5dc1c1ab/EliteAPI/Event/Models/LoadGameEvent.cs#L14). 

Thanks for your report!
